name: nodejs-project
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'  
  workflow_dispatch: {}
env:
  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
jobs:
  nodejs-tests:
    runs-on: ubuntu-latest  
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node- 

      - name: npm-installation
        run: npm ci    
      - name: Run tests
        run: npm test
      - name: Checkout repository
        run: echo "Tests are done............"
  Build:
    runs-on: ubuntu-latest
    needs: nodejs-tests
    outputs:
      scriptfile: ${{ steps.publish-js.outputs.scriptfile }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4 
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-  
      - name: npm-installation
        run: npm install 
      - name: build-project
        run: npm run build
      - name: build-project
        run: echo "Build is done........"
      - name: Publish js filename
        id: publish-js
        run: find dist/assets/*.js -type f -execdir echo 'scriptfile={}' >> $GITHUB_OUTPUT ';'
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact  
          path: |
            dist/
            package.json
  Deployment:
    runs-on: ubuntu-latest
    needs: Build
    steps: 
      - name: build-project
        run: echo "Deployment Done........"
      - name: Output-message
        run: echo "${{toJson(github)}}"
      - name: Download-artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          # path: ./dist
      - name: Output-message
        run: ls
      - name: Output-filename
        run: echo "${{ needs.Build.outputs.scriptfile }}"
      - name: env-check
        run: echo "MONGODB_USERNAME is ${{ env.MONGODB_USERNAME }}"  