name: nodejs-project
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'  
jobs:
  nodejs-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm-installation
        run: npm ci    
      - name: Run tests
        run: npm test
      - name: Checkout repository
        run: echo "Tests are done........"
  Build:
    runs-on: ubuntu-latest
    needs: nodejs-tests
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4 
      - name: npm-installation
        run: npm install 
      - name: build-project
        run: npm run build
      - name: build-project
        run: echo "Build is done........"
  Deployment:
    runs-on: ubuntu-latest
    needs: Build
    steps: 
      - name: build-project
        run: echo "Deployment Done........"
      - name: Output-message
        run: echo "${{toJson(github)}}"
