name: nodejs-project
on: push
jobs:
  nodejs-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tests
        run: npm test
      - name: Checkout repository
        run: echo "Tests are done........"
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4 
      - name: npm-installation
        run: npm ci  
      - name: build-project
        run: npm run build
      - name: build-project
        run: sh "echo Build is done........"
  Deployement:
    runs-on: ubuntu-latest
    steps: 
      - name: build-project
        run: echo "Deployement Done........"   

