name: nodejs-project
on: push
jobs:
  nodejs-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        run: echo "checkout repository........"
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4 
      - name: npm-installation
        run: npm ci  
      - name: build-project
        run: npm run build
  Deployement:
    runs-on: ubuntu-latest
    steps: 
      - name: build-project
        run: echo "Deployement Done........"   

