name: nodejs-project
on: push
jobs:
  stage-01:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4  
      - name: npm-installation
        run: npm ci
      - name: run-tests
        run: npm test  

